---
- name: Configure CSR 1000v Switches
  hosts: csr1000v
  gather_facts: no
  tasks:
    - name: Enable OSPF on interfaces
      cisco.ios.ios_config:
        lines:
          - ip address "{{ item.ip_address }} {{ item.subnet }}"
          - no shutdown
        parents:
          - interface GigabitEthernet 2
      loop:
        - { ip_address: '172.16.1.1', subnet: '255.255.255.0', host: 'csr1000v-1' }
        - { ip_address: '192.168.1.1', subnet: '255.255.255.0', host: 'csr1000v-2' }
      when: "item.host == inventory_hostname"

    - name: Configure OSPF
      cisco.ios.ios_config:
        lines:
          - exit
          - router ospf 1
          - network 0.0.0.0 255.255.255.255 area 0
        save_when: modified

    - name: Configure DHCP on switches
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool {{ item.pool_name }}
          - network {{ item.network }} {{ item.subnet }}
          - default-router {{ item.default_router }}
          - dns-server 8.8.8.8 8.8.4.4
          - lease 1 0 0
          - ip dhcp excluded-address {{ item.excluded_start }} {{ item.excluded_end }}
          - domain-name example.com
        save_when: modified
      loop:
        - { pool_name: '172-dhcp-range', network: '172.16.1.0', subnet: '255.255.255.0', default_router: '172.16.1.1', excluded_start: '172.16.1.1', excluded_end: '172.16.1.10', host: 'csr1000v-1' }
        - { pool_name: '192-dhcp-range', network: '192.168.1.0', subnet: '255.255.255.0', default_router: '192.168.1.1', excluded_start: '192.168.1.1', excluded_end: '192.168.1.10', host: 'csr1000v-2' }
      when: "item.host == inventory_hostname"
