- name: Gather IOS facts
  hosts: csr1000v
  gather_facts: yes
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
  tasks:
    - name: Get IOS facts
      cisco.ios.ios_facts:
      register: ios_facts
    - name: Print IOS facts
      debug:
        var: ios_facts

    - name: Gather legacy and resource facts
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: all
      register: legacy_facts
    - name: Print legacy and resource facts
      debug:
        var: legacy_facts
