---
- name: Ping a host
  hosts: csr1000v
  gather_facts: no
  vars:
    ping_host_1: 192.168.1.174  
    ping_host_2: 192.168.1.171  
  tasks:
    - name: Ping the host
      cisco.ios.ios_ping:
        dest: 
        - "{{ ping_host_1 }}"