---
- name: Ping a host
  hosts: csr1000v
  gather_facts: no
  vars:
    ansible_user: cisco
    ansible_password: cisco
    #ansible_python_interpreter: /usr/bin/python3.6
    #ansible_connection: network_cli
    #ansible_network_os: ios
    ping_host: 192.168.1.171    
  tasks:
    - name: Ping the host
      cisco.ios.ios_ping:
        dest: "{{ ping_host }}"