---
- name: Configure CSR 1000v Switches
  hosts: csr1000v-1a, csr1000v-2a
  gather_facts: no
  tasks:
    - name: Show IP interface brief
      ios_command:
        commands: "show ip interface brief"
      register: show_ip_int_brief

    - name: Show IP OSPF neighbor
      ios_command:
        commands: "show ip ospf neighbor"
      register: show_ip_ospf_neighbor
      
    # - name: Wait for 45 seconds
    #   pause:
    #   seconds: 45
      
    - name: Show IP DHCP pool
      ios_command:
        commands: "show ip dhcp pool"
      register: show_ip_dhcp_pool
      
    - name: Show IP DHCP binding
      ios_command:
        commands: "show ip dhcp binding"
      register: show_ip_dhcp_binding
      
    - name: Print results
      debug:
        var: item.stdout_lines
      with_items:
        - "{{ show_ip_int_brief.stdout }}"
        - "{{ show_ip_ospf_neighbor.stdout }}"
        - "{{ show_ip_dhcp_pool.stdout }}"
        - "{{ show_ip_dhcp_binding.stdout }}"
