---
- name: Configure CSR 1000v Switches
  hosts: csr1000v-1a, csr1000v-2a
  gather_facts: no
  tasks:
    - name: Enable OSPF on csr1000v-1a
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              areas:
                - area_id: "0"
              network:
                - address: 0.0.0.0
                  wildcard_bits: 255.255.255.255
                  area: 0
        state: replaced
      delegate_to: csr1000v-1a


    - name: Enable OSPF on csr1000v-2a
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              areas:
                - area_id: "0"
              network:
                - address: 0.0.0.0
                  wildcard_bits: 255.255.255.255
                  area: 0
        state: replaced
      delegate_to: csr1000v-2a